name: qr_code_generator
description: "QR code gernerator"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  flutter: 3.38.5
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  image_picker: ^1.2.1
  widgets_to_image: ^2.0.1
  universal_html: ^2.3.0
  file_saver: ^0.3.1
  file_picker: ^10.3.8
  flutter_bloc: ^9.1.1
  pretty_qr_code: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true